// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240807075313_AddedNewColumnTarget")]
    partial class AddedNewColumnTarget
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("DataAccess.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("group")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SharedLibrary.Entities.Alarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlarmCodeId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlarmCodeId");

                    b.ToTable("Alarm");
                });

            modelBuilder.Entity("SharedLibrary.Entities.AlarmCode", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Alarm_Code");
                });

            modelBuilder.Entity("SharedLibrary.Entities.AuxTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxMaxValue")
                        .HasColumnType("int");

                    b.Property<int>("MaxValue")
                        .HasColumnType("int");

                    b.Property<string>("MeasurementUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinMinVaue")
                        .HasColumnType("int");

                    b.Property<int>("MinVaue")
                        .HasColumnType("int");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aux_table");
                });

            modelBuilder.Entity("SharedLibrary.Entities.DynamicData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("InletFlow")
                        .HasColumnType("real");

                    b.Property<float>("InletFlowLinModel")
                        .HasColumnType("real");

                    b.Property<float>("InletFlowNonLinModel")
                        .HasColumnType("real");

                    b.Property<bool>("IsPumpActive")
                        .HasColumnType("bit");

                    b.Property<float>("OutletFlow")
                        .HasColumnType("real");

                    b.Property<int>("Sample")
                        .HasColumnType("int");

                    b.Property<float>("Target")
                        .HasColumnType("real");

                    b.Property<float>("ValvePositionFeedback")
                        .HasColumnType("real");

                    b.Property<float>("WaterLevelTank1")
                        .HasColumnType("real");

                    b.Property<float>("WaterLevelTank1LinModel")
                        .HasColumnType("real");

                    b.Property<float>("WaterLevelTank1NonLinModel")
                        .HasColumnType("real");

                    b.Property<float>("WaterLevelTank2")
                        .HasColumnType("real");

                    b.Property<float>("WaterLevelTank2LinModel")
                        .HasColumnType("real");

                    b.Property<float>("WaterLevelTank2NonLinModel")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("DynamicData");
                });

            modelBuilder.Entity("SharedLibrary.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DequeueDT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnqueueDT")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorLog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("SharedLibrary.Entities.MessageHeader", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Message_Header");
                });

            modelBuilder.Entity("SharedLibrary.Entities.ModelParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Theta1")
                        .HasColumnType("float");

                    b.Property<double>("Theta2")
                        .HasColumnType("float");

                    b.Property<double>("Theta3")
                        .HasColumnType("float");

                    b.Property<double>("Theta4")
                        .HasColumnType("float");

                    b.Property<double>("Theta5")
                        .HasColumnType("float");

                    b.Property<double>("Theta6")
                        .HasColumnType("float");

                    b.Property<double>("Theta7")
                        .HasColumnType("float");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ModelParameters");
                });

            modelBuilder.Entity("SharedLibrary.Entities.Alarm", b =>
                {
                    b.HasOne("SharedLibrary.Entities.AlarmCode", "AlarmCode")
                        .WithMany("Alarms")
                        .HasForeignKey("AlarmCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlarmCode");
                });

            modelBuilder.Entity("SharedLibrary.Entities.Message", b =>
                {
                    b.HasOne("SharedLibrary.Entities.MessageHeader", "MessageHeader")
                        .WithMany("Alarms")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessageHeader");
                });

            modelBuilder.Entity("SharedLibrary.Entities.AlarmCode", b =>
                {
                    b.Navigation("Alarms");
                });

            modelBuilder.Entity("SharedLibrary.Entities.MessageHeader", b =>
                {
                    b.Navigation("Alarms");
                });
#pragma warning restore 612, 618
        }
    }
}
